import { Product, Review } from "./types";

const PRODUCT_CATALOG: Product[] = [
  // SKINCARE
  {
    id: "p01",
    slug: "radiant-glow-vitamin-c-serum",
    brand: "Judah Botanicals",
    name: "Radiant Glow Vitamin C Serum",
    category: "skincare",
    price: 2800,
    oldPrice: 3500,
    rating: 4.8,
    reviewsCount: 212,
    stock: 34,
    badges: ["BEST SELLER", "SALE"],
    image: "/images/products/ahabhatheordinary.jpg",
    description:
      "A fast-absorbing brightening serum with 15% stabilised vitamin C, built to even out tone and fade the look of dark spots over time.",
    benefits: [
      "Visibly brightens and evens skin tone",
      "Softens the look of dark spots and scarring",
      "Antioxidant protection against daily environmental stress",
      "Lightweight, non-greasy finish under makeup",
    ],
    ingredients:
      "Aqua, 15% Ascorbic Acid, Ferulic Acid, Vitamin E, Hyaluronic Acid, Glycerin, Panthenol.",
    howToUse:
      "Apply 3–4 drops to clean, dry skin every morning before moisturiser and SPF. Patch test before first use.",
  },
  {
    id: "p02",
    slug: "hydra-renew-snail-mucin-essence",
    brand: "Nuru Beauty",
    name: "Hydra-Renew Snail Mucin Essence",
    category: "skincare",
    price: 2600,
    oldPrice: 3200,
    rating: 4.7,
    reviewsCount: 178,
    stock: 41,
    badges: ["SALE"],
    image: "/images/products/aloecleanser.jpg",
   description:
      "A 96% snail secretion filtrate essence that deeply hydrates, repairs the moisture barrier and leaves skin plump and dewy.",
    benefits: [
      "Deep, lasting hydration",
      "Supports barrier repair and skin recovery",
      "Improves texture and softens fine lines",
      "Fragrance-free, suitable for sensitive skin",
    ],
    ingredients: "Snail Secretion Filtrate 96%, Betaine, Sodium Hyaluronate, Panthenol, Arginine.",
    howToUse: "Pat 2–3 pumps onto skin after cleansing and toning, morning and night.",
  },
  {
    id: "p03",
    slug: "charcoal-clay-detox-mask",
    brand: "Zawadi Naturals",
    name: "Charcoal Clay Detox Mask",
    category: "skincare",
    price: 1800,
    rating: 4.5,
    reviewsCount: 96,
    stock: 58,
    badges: ["NEW"],
    image: "/images/products/aloemoisturizer.jpg",
    description:
      "An activated-charcoal and kaolin clay mask that draws out impurities and excess oil for a clearer, mattified complexion.",
    benefits: [
      "Deep-cleans congested pores",
      "Controls shine and excess oil",
      "Softens skin texture",
      "10-minute weekly treatment",
    ],
    ingredients: "Activated Charcoal, Kaolin Clay, Bentonite Clay, Aloe Vera, Tea Tree Oil.",
    howToUse: "Apply an even layer to clean skin, avoiding the eye area. Leave for 10 minutes and rinse with warm water. Use 1–2 times weekly.",
  },
  {
    id: "p04",
    slug: "overnight-retinol-recovery-cream",
    brand: "Lion of Judah",
    name: "Overnight Retinol Recovery Cream",
    category: "skincare",
    price: 3400,
    rating: 4.9,
    reviewsCount: 145,
    stock: 22,
    badges: ["BEST SELLER"],
    image: "/images/products/aloeserumrashel.jpg",
    description:
      "A gentle encapsulated-retinol night cream that supports cell renewal while you sleep, waking up to visibly smoother skin.",
    benefits: [
      "Supports overnight skin renewal",
      "Softens the look of fine lines",
      "Rich, barrier-supporting formula",
      "Non-irritating encapsulated retinol",
    ],
    ingredients: "Encapsulated Retinol, Squalane, Shea Butter, Ceramides, Niacinamide.",
    howToUse: "Apply a pea-sized amount to the face at night after cleansing. Start 2–3 times weekly and build up tolerance. Always wear SPF by day.",
  },
  {
    id: "p05",
    slug: "niacinamide-10-zinc-serum",
    brand: "Simba Skin Co.",
    name: "Niacinamide 10% + Zinc 1% Serum",
    category: "skincare",
    price: 1450,
    rating: 4.6,
    reviewsCount: 301,
    stock: 76,
    badges: [],
    image: "/images/products/aloetoner.jpg",
    description:
      "A high-strength niacinamide serum that visibly reduces the appearance of blemishes and balances congested, oily skin.",
    benefits: [
      "Reduces the look of enlarged pores",
      "Balances oil production",
      "Visibly clears blemish-prone skin",
      "Lightweight, quick-absorbing texture",
    ],
    ingredients: "Niacinamide 10%, Zinc PCA 1%, Aqua, Glycerin, Tamarindus Indica Seed Gum.",
    howToUse: "Apply a few drops to face morning and evening after cleansing, before heavier creams.",
  },
  {
    id: "p06",
    slug: "rose-quartz-hydrating-toner",
    brand: "Judah Botanicals",
    name: "Rose Quartz Hydrating Toner",
    category: "skincare",
    price: 1600,
    oldPrice: 2000,
    rating: 4.4,
    reviewsCount: 58,
    stock: 4,
    badges: ["SALE", "LOW STOCK"],
    image: "/images/products/asgel.jpg",
    description:
      "An alcohol-free rosewater toner that preps skin for serums while delivering a light veil of hydration and calm.",
    benefits: [
      "Preps skin to absorb serums better",
      "Soothes and refreshes on contact",
      "Alcohol-free, non-drying formula",
    ],
    ingredients: "Rosa Damascena Flower Water, Glycerin, Aloe Barbadensis Leaf Juice, Panthenol.",
    howToUse: "Sweep across the face with a cotton pad or press in with hands after cleansing.",
  },

  // BODYCARE
  {
    id: "p07",
    slug: "shea-cocoa-body-butter",
    brand: "Zawadi Naturals",
    name: "Shea & Cocoa Body Butter",
    category: "bodycare",
    price: 1900,
    rating: 4.8,
    reviewsCount: 234,
    stock: 64,
    badges: ["BEST SELLER"],
    image: "/images/products/batanaconditioner.jpg",
   description:
      "A rich whipped butter blending raw shea and cocoa butter to seal in moisture for up to 48 hours of softness.",
    benefits: [
      "Deeply nourishes dry, thirsty skin",
      "Long-lasting softness, up to 48 hours",
      "Rich, fast-melting texture",
      "Sealed with a light, warm scent",
    ],
    ingredients: "Shea Butter, Cocoa Butter, Coconut Oil, Vitamin E, Sweet Almond Oil.",
    howToUse: "Scoop a small amount and massage into skin after showering while still slightly damp.",
  },
  {
    id: "p08",
    slug: "coffee-bean-exfoliating-scrub",
    brand: "Amani Wellness",
    name: "Coffee Bean Exfoliating Scrub",
    category: "bodycare",
    price: 1600,
    rating: 4.6,
    reviewsCount: 87,
    stock: 49,
    badges: ["NEW"],
    image: "/images/products/batanacream.jpg",

    description:
      "A firming coffee and brown sugar scrub that buffs away dry, dull skin and leaves a smooth, energised finish.",
    benefits: [
      "Buffs away dry, flaky skin",
      "Supports smoother-looking skin over time",
      "Invigorating coffee aroma",
    ],
    ingredients: "Coffea Arabica (Coffee) Seed Powder, Brown Sugar, Coconut Oil, Vitamin E.",
    howToUse: "Massage onto damp skin in circular motions 2–3 times weekly, then rinse thoroughly.",
  },
  {
    id: "p09",
    slug: "cocoa-radiance-body-oil",
    brand: "Lion of Judah",
    name: "Cocoa Radiance Body Oil",
    category: "bodycare",
    price: 2200,
    rating: 4.7,
    reviewsCount: 112,
    stock: 37,
    badges: [],
    image: "/images/products/collagenburn.jpg",

    description:
      "A fast-absorbing dry oil that leaves skin with a soft, luminous sheen without any greasy residue.",
    benefits: [
      "Non-greasy, fast-absorbing finish",
      "Leaves a natural, luminous glow",
      "Light cocoa fragrance",
    ],
    ingredients: "Sweet Almond Oil, Jojoba Oil, Theobroma Cacao (Cocoa) Extract, Vitamin E.",
    howToUse: "Massage a few drops over damp or dry skin, focusing on elbows, knees and legs.",
  },
  {
    id: "p10",
    slug: "whipped-mango-body-cream",
    brand: "Nuru Beauty",
    name: "Whipped Mango Body Cream",
    category: "bodycare",
    price: 1750,
    oldPrice: 2100,
    rating: 4.5,
    reviewsCount: 76,
    stock: 52,
    image: "/images/products/cosrxcream1.jpg",
    badges: ["SALE"],
    description:
      "A light, fluffy body cream with mango butter that sinks in quickly for everyday hydration with a fruity finish.",
    benefits: [
      "Quick-absorbing, all-day hydration",
      "Light, fluffy whipped texture",
      "Fresh mango scent",
    ],
    ingredients: "Mango Seed Butter, Glycerin, Aqua, Vitamin E, Sunflower Seed Oil.",
    howToUse: "Apply generously all over the body after bathing.",
  },

  // HAIRCARE
  {
    id: "p11",
    slug: "rice-water-strengthening-shampoo",
    brand: "Kesi & Co",
    name: "Rice Water Strengthening Shampoo",
    category: "haircare",
    price: 1500,
    rating: 4.6,
    reviewsCount: 190,
    stock: 66,
    badges: ["BEST SELLER"],
    image: "/images/products/cosrxhyaluronic1.jpg",
    description:
      "A sulphate-free shampoo infused with fermented rice water to gently cleanse while strengthening strands from root to tip.",
    benefits: [
      "Gently cleanses without stripping",
      "Strengthens hair and reduces breakage",
      "Sulphate-free and colour-safe",
    ],
    ingredients: "Fermented Rice Water, Aqua, Coco-Glucoside, Panthenol, Biotin.",
    howToUse: "Massage into wet hair and scalp, lather, then rinse thoroughly. Follow with conditioner.",
  },
  {
    id: "p12",
    slug: "rice-water-repair-conditioner",
    brand: "Kesi & Co",
    name: "Rice Water Repair Conditioner",
    category: "haircare",
    price: 1500,
    rating: 4.6,
    reviewsCount: 165,
    stock: 61,
    badges: [],
    image: "/images/products/cosrxlowphcleanser.jpg",
    description:
      "A deeply conditioning pair to the Rice Water Shampoo, smoothing the cuticle and detangling with ease.",
    benefits: [
      "Smooths and detangles",
      "Seals in moisture and shine",
      "Reduces breakage from brushing",
    ],
    ingredients: "Fermented Rice Water, Cetearyl Alcohol, Behentrimonium Chloride, Panthenol.",
    howToUse: "Apply from mid-length to ends after shampooing. Leave for 2–3 minutes and rinse.",
  },
  {
    id: "p13",
    slug: "castor-biotin-growth-oil",
    brand: "Judah Botanicals",
    name: "Castor & Biotin Growth Oil",
    category: "haircare",
    price: 1300,
    oldPrice: 1600,
    rating: 4.9,
    reviewsCount: 402,
    stock: 88,
    badges: ["SALE", "BEST SELLER"],
    image: "/images/products/cosrxsalicylic1.jpg",
    description:
      "A scalp-nourishing blend of Jamaican black castor oil and biotin, formulated to support fuller, healthier-looking hair.",
    benefits: [
      "Nourishes the scalp",
      "Supports the look of fuller, thicker hair",
      "Adds shine and softness",
    ],
    ingredients: "Jamaican Black Castor Oil, Biotin, Rosemary Oil, Peppermint Oil, Jojoba Oil.",
    howToUse: "Massage into the scalp 2–3 times weekly, or apply to lengths and ends to seal moisture.",
  },
  {
    id: "p14",
    slug: "silk-protein-leave-in-cream",
    brand: "Lion of Judah",
    name: "Silk Protein Leave-In Cream",
    category: "haircare",
    price: 1650,
    rating: 4.4,
    reviewsCount: 63,
    stock: 40,
    badges: ["NEW"],
    image: "/images/products/cosrxtonerPoweressence1.jpg",
    description:
      "A lightweight leave-in cream with silk amino acids that defines, softens and controls frizz without weigh-down.",
    benefits: [
      "Controls frizz and flyaways",
      "Softens and adds definition",
      "Lightweight, no product build-up",
    ],
    ingredients: "Hydrolysed Silk Protein, Aqua, Shea Butter, Glycerin, Argan Oil.",
    howToUse: "Apply to damp hair from mid-length to ends before styling.",
  },

  // WELLNESS
  {
    id: "p15",
    slug: "lavender-calm-roll-on",
    brand: "Amani Wellness",
    name: "Lavender Calm Roll-On",
    category: "wellness",
    price: 950,
    rating: 4.7,
    reviewsCount: 88,
    stock: 70,
    badges: [],
    image: "/images/products/flattummygummies.jpg",
    description:
      "A pocket-sized aromatherapy roll-on blending lavender and chamomile essential oils for on-the-go calm.",
    benefits: [
      "Soothing, portable aromatherapy",
      "Convenient roll-on application",
      "Blended with skin-safe carrier oils",
    ],
    ingredients: "Lavandula Angustifolia Oil, Chamomilla Recutita Oil, Fractionated Coconut Oil.",
    howToUse: "Roll onto pulse points — wrists, temples and neck — as needed.",
  },
  {
    id: "p16",
    slug: "collagen-beauty-gummies",
    brand: "Amani Wellness",
    name: "Collagen Beauty Gummies",
    category: "wellness",
    price: 2400,
    rating: 4.5,
    reviewsCount: 121,
    stock: 45,
    badges: ["NEW"],
    image: "/images/products/glycolictheordinary.jpg",
    description:
      "Daily beauty gummies with marine collagen, biotin and vitamin C to support skin, hair and nail wellness from within.",
    benefits: [
      "Supports skin elasticity from within",
      "Contains biotin for hair and nails",
      "Easy daily gummy format",
    ],
    ingredients: "Marine Collagen Peptides, Biotin, Vitamin C, Vitamin E, Pectin.",
    howToUse: "Take two gummies daily, with or without food.",
  },
  {
    id: "p17",
    slug: "detox-herbal-tea-blend",
    brand: "Lion of Judah",
    name: "Detox Herbal Tea Blend",
    category: "wellness",
    price: 1100,
    rating: 4.3,
    reviewsCount: 40,
    stock: 54,
    badges: [],
    image: "/images/products/lacticacidtheordinary.jpg",
    description:
      "A caffeine-free herbal blend of ginger, lemongrass and hibiscus designed to support gentle daily wellness rituals.",
    benefits: ["Caffeine-free daily ritual", "Warming ginger and lemongrass blend", "20 individually sealed sachets"],
    ingredients: "Ginger Root, Lemongrass, Hibiscus, Green Tea Leaf, Lemon Peel.",
    howToUse: "Steep one sachet in hot water for 5–7 minutes.",
  },
  {
    id: "p18",
    slug: "magnesium-sleep-mist",
    brand: "Judah Botanicals",
    name: "Magnesium Sleep Mist",
    category: "wellness",
    price: 1350,
    oldPrice: 1600,
    rating: 4.6,
    reviewsCount: 55,
    stock: 33,
    badges: ["SALE"],
    image: "/images/products/medicubecream.jpg",
    description:
      "A calming pillow and body mist combining magnesium with lavender and cedarwood to wind down before bed.",
    benefits: ["Part of a calming wind-down ritual", "Lavender and cedarwood aroma", "Alcohol-free mist"],
    ingredients: "Magnesium Chloride, Aqua, Lavandula Oil, Cedarwood Oil, Glycerin.",
    howToUse: "Mist lightly over pillows and skin 15 minutes before bed.",
  },

  // MAKEUP
  {
    id: "p19",
    slug: "velvet-matte-liquid-lipstick",
    brand: "Adaeze Naturals",
    name: "Velvet Matte Liquid Lipstick",
    category: "makeup",
    price: 1400,
    rating: 4.7,
    reviewsCount: 210,
    stock: 80,
    badges: ["BEST SELLER"],
    image: "/images/products/medicubemild.jpg",

    description:
      "A long-wearing, transfer-resistant liquid lipstick that dries down to a soft-focus matte finish in one swipe.",
    benefits: ["Up to 8 hours of wear", "Transfer-resistant matte finish", "Comfortable, non-drying formula"],
    ingredients: "Dimethicone, Isododecane, Silica, Vitamin E, Iron Oxides.",
    howToUse: "Apply from the centre of the lips outward. Let dry for 60 seconds without rubbing.",
  },
  {
    id: "p20",
    slug: "featherweight-foundation-spf30",
    brand: "Adaeze Naturals",
    name: "Featherweight Foundation SPF 30",
    category: "makeup",
    price: 2600,
    rating: 4.8,
    reviewsCount: 267,
    stock: 58,
    badges: ["BEST SELLER"],
    image: "/images/products/medicubeserum.jpg",
    description:
      "A buildable, skin-like foundation with SPF 30 that evens out tone while letting natural texture show through.",
    benefits: ["Buildable, natural-finish coverage", "Broad-spectrum SPF 30 protection", "Available across 24 shades"],
    ingredients: "Aqua, Titanium Dioxide (SPF), Dimethicone, Glycerin, Niacinamide.",
    howToUse: "Apply with a brush, sponge or fingertips, building coverage where needed.",
  },
  {
    id: "p21",
    slug: "radiant-skin-tint",
    brand: "Nuru Beauty",
    name: "Radiant Skin Tint",
    category: "makeup",
    price: 2100,
    oldPrice: 2500,
    rating: 4.5,
    reviewsCount: 94,
    stock: 5,
    badges: ["SALE", "NEW", "LOW STOCK"],
    image: "/images/products/medicubewrapmask.jpg",
    description:
      "A sheer, glow-boosting skin tint that evens tone with a dewy finish for a barely-there, skin-first look.",
    benefits: ["Sheer, buildable glow", "Dewy, hydrated finish", "Lightweight, skincare-infused formula"],
    ingredients: "Aqua, Glycerin, Hyaluronic Acid, Mica, Iron Oxides.",
    howToUse: "Warm a small amount between fingertips and press into skin.",
  },
  {
    id: "p22",
    slug: "sculpt-glow-bronzer-duo",
    brand: "Lion of Judah",
    name: "Sculpt & Glow Bronzer Duo",
    category: "makeup",
    price: 1900,
    rating: 4.6,
    reviewsCount: 132,
    stock: 44,
    image: "/images/products/miellemasque.jpg",
    badges: [],
    description:
      "A two-tone bronzer and highlighter duo designed to sculpt and lift with a soft, natural-looking glow.",
    benefits: ["Sculpts and warms the complexion", "Soft, blendable powder formula", "Buildable highlight finish"],
    ingredients: "Talc, Mica, Dimethicone, Silica, Iron Oxides.",
    howToUse: "Buff the bronzer along cheekbones and jawline. Tap the highlighter onto high points of the face.",
  },

  // FRAGRANCE
  {
    id: "p23",
    slug: "amber-oud-eau-de-parfum",
    brand: "Lion of Judah",
    name: "Amber & Oud Eau de Parfum",
    category: "fragrance",
    price: 4500,
    rating: 4.9,
    reviewsCount: 188,
    stock: 26,
    image: "/images/products/mielleshampoo.jpg",
    badges: ["BEST SELLER"],
    description:
      "A signature warm, woody fragrance built around amber and oud with a soft musk dry-down that lasts all day.",
    benefits: ["Long-lasting, 8+ hour wear", "Warm amber and oud signature", "50ml eau de parfum concentration"],
    ingredients: "Alcohol Denat., Parfum, Amber Accord, Oud Accord, Musk.",
    howToUse: "Spray onto pulse points — wrists and neck — after showering.",
  },
  {
    id: "p24",
    slug: "wild-jasmine-body-mist",
    brand: "Judah Botanicals",
    name: "Wild Jasmine Body Mist",
    category: "fragrance",
    price: 1200,
    rating: 4.4,
    reviewsCount: 71,
    stock: 63,
    image: "/images/products/moisturizingfactor.jpg",
    badges: ["NEW"],
    description:
      "A light, layerable body mist with fresh jasmine and white musk, perfect for everyday spritzing.",
    benefits: ["Light, everyday layering scent", "Refreshing jasmine and musk", "200ml — generous, spray-happy size"],
    ingredients: "Aqua, Alcohol Denat., Parfum, Jasminum Officinale Extract.",
    howToUse: "Mist generously over body after bathing, reapply as needed.",
  },
  {
    id: "p25",
    slug: "citrus-bloom-eau-de-toilette",
    brand: "Zawadi Naturals",
    name: "Citrus Bloom Eau de Toilette",
    category: "fragrance",
    price: 3200,
    oldPrice: 3800,
    rating: 4.6,
    reviewsCount: 99,
    stock: 31,
    badges: ["SALE"],
    image: "/images/products/niacinamidetheordinary.jpg",
    description:
      "A bright, uplifting citrus fragrance with notes of bergamot and neroli, finished with a soft floral heart.",
    benefits: ["Bright, energising citrus opening", "Soft floral heart", "35ml eau de toilette"],
    ingredients: "Alcohol Denat., Parfum, Bergamot Oil, Neroli Extract, Musk.",
    howToUse: "Spray onto pulse points, avoiding direct sunlight on freshly sprayed skin.",
  },

  // BEAUTY TOOLS
  {
    id: "p26",
    slug: "jade-facial-roller-gua-sha-set",
    brand: "Lion of Judah",
    name: "Jade Facial Roller & Gua Sha Set",
    category: "beauty-tools",
    price: 1500,
    rating: 4.7,
    reviewsCount: 143,
    stock: 47,
    image: "/images/products/rashel3in1.jpg",
    badges: ["BEST SELLER"],
    description:
      "A genuine jade roller and gua sha set designed to support your skincare routine with a cooling, de-puffing massage.",
    benefits: ["Supports lymphatic-style facial massage", "Cooling jade surface", "Pairs well with facial oils and serums"],
    ingredients: "Natural Jade Stone.",
    howToUse: "Roll or glide gently upward and outward across the face after applying serum or oil.",
  },
  {
    id: "p27",
    slug: "silicone-facial-cleansing-brush",
    brand: "Nuru Beauty",
    name: "Silicone Facial Cleansing Brush",
    category: "beauty-tools",
    price: 1200,
    rating: 4.3,
    reviewsCount: 52,
    stock: 39,
    image: "/images/products/rashelfacecream.jpg",
    badges: ["NEW"],
    description:
      "A soft-silicone, rechargeable cleansing brush that lifts away makeup and buildup for a deeper daily cleanse.",
    benefits: ["Gentle, hygienic silicone bristles", "USB rechargeable", "Waterproof for shower use"],
    ingredients: "Food-grade Silicone, ABS Plastic.",
    howToUse: "Apply cleanser to damp skin, massage with the brush for 60 seconds, then rinse.",
  },
  {
    id: "p28",
    slug: "rose-gold-makeup-brush-set-12pc",
    brand: "Lion of Judah",
    name: "Rose Gold Makeup Brush Set (12pc)",
    category: "beauty-tools",
    price: 2800,
    oldPrice: 3400,
    rating: 4.8,
    reviewsCount: 176,
    stock: 6,
    image: "/images/products/rashelserumvc.jpg",
    badges: ["SALE", "LOW STOCK"],
    description:
      "A complete 12-piece brush set with soft synthetic bristles for flawless base, eye and contour application.",
    benefits: ["Full face and eye brush coverage", "Soft, cruelty-free synthetic bristles", "Comes with a travel case"],
    ingredients: "Synthetic Fibre Bristles, Aluminium Ferrule, Wooden Handle.",
    howToUse: "Use the labelled guide on the case to match each brush to its ideal step in your routine.",
  },
];

const CATEGORY_IMAGES: Record<Product["category"], string> = {
  skincare: "/images/skincare1.jpg",
  bodycare: "/images/bodycare1.jpg",
  haircare: "/images/haircare1.jpg",
  wellness: "/images/wellness1.jpg",
  makeup: "/images/makeup1.jpg",
  fragrance: "/images/hero2.jpeg",
  "beauty-tools": "/images/hero1.jpeg",
};

export const PRODUCTS: Product[] = PRODUCT_CATALOG.map((product) => ({
  ...product,
  image: product.image || CATEGORY_IMAGES[product.category],
}));

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getRelatedProducts(product: Product, count = 4): Product[] {
  return PRODUCTS.filter((p) => p.category === product.category && p.id !== product.id).slice(0, count);
}

export function getBestSellers(count = 8): Product[] {
  return PRODUCTS.filter((p) => p.badges.includes("BEST SELLER")).slice(0, count);
}

export function getNewArrivals(count = 8): Product[] {
  return PRODUCTS.filter((p) => p.badges.includes("NEW")).slice(0, count);
}

export function getDeals(count = 8): Product[] {
  return PRODUCTS.filter((p) => p.badges.includes("SALE")).slice(0, count);
}

export const REVIEWS: Review[] = [
  {
    id: "r1",
    name: "Wanjiru K.",
    rating: 5,
    text: "The Vitamin C serum genuinely changed my skin in three weeks. Ordering on WhatsApp was so easy — I had it delivered to Kilimani the next day.",
    verified: true,
  },
  {
    id: "r2",
    name: "Amina H.",
    rating: 5,
    text: "The Castor & Biotin oil is a repurchase for life. My edges have never been thicker. Customer service on WhatsApp answered every question I had.",
    verified: true,
  },
  {
    id: "r3",
    name: "Brenda A.",
    rating: 4,
    text: "Love the Shea & Cocoa body butter, smells incredible and lasts all day. Delivery to Mombasa took two days but was well packaged.",
    verified: true,
  },
  {
    id: "r4",
    name: "Faith N.",
    rating: 5,
    text: "The Amber & Oud perfume gets me compliments every single time. Packaging feels genuinely premium for the price.",
    verified: true,
  },
  {
    id: "r5",
    name: "Grace M.",
    rating: 5,
    text: "Foundation matched my shade perfectly and the WhatsApp team helped me pick it before I even ordered. Will be shopping here again.",
    verified: true,
  },
  {
    id: "r6",
    name: "Njeri W.",
    rating: 4,
    text: "Fast, easy checkout straight through WhatsApp. No confusing forms — just sent my order and confirmed delivery in minutes.",
    verified: true,
  },
];
